#!/bin/bash

if [ -z "$*" ]; then
  echo "Arguments are missing (gMPXV-2024 -h for help)"
  exit 0
fi

if [ -z "$2" ]; then
CPU=$(nproc)
else
CPU=$2
fi

while getopts ":hv:" opt; do
	case $opt in
                 h)
                       echo "Usage : gMPXV-2024 -options(-h display this help, -v \"viruses\" MPXV, VV) [fastqPrefix] [nb of cpu]"
                       exit 0
                       ;;
                 v)
                      echo  "Virus : $OPTARG"
                      virus=$OPTARG
                      shift $((OPTIND-1))
                      ;;
		\?)
			echo "Unknown option $OPTARG" >&2
			;;
	esac
done

# main

fastq2consensus.sh $1 $CPU $virus $4 2>"$1".log

exit 0
