#!/bin/bash



SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )"

if [ -z "$*" ]; then
  echo "Arguments are missing (gMPXV-2025 -h for help)"
  exit 0
fi
amplicon="false"
virus=""

while getopts "hv:a" opt; do
  case $opt in
    h)
      echo "Usage : gMPXV-2025 -h (help) -v <virus> -a (amplicon mode) [fastqPrefix] [nb of cpu]"
      exit 0
      ;;
    v)
      virus=$OPTARG
      ;;
    a)
      amplicon="true"
      ;;
    \?)
      echo "Unknown option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Remove options from positional args
shift $((OPTIND - 1))

# Positional arguments
FASTQ_PREFIX=$1
CPU=${2:-$(nproc)}

# Debug prints
echo "FASTQ prefix: $FASTQ_PREFIX"
echo "CPU: $CPU"
echo "Virus: $virus"
echo "Amplicon mode: $amplicon"

# Call downstream script
bash "$SCRIPT_DIR/fastq2consensus.sh" "$FASTQ_PREFIX" "$CPU" "$virus" "$amplicon" 2>"$FASTQ_PREFIX.log"